<a href="https://colab.research.google.com/github/longjae/pytorch_study/blob/master/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor
- 텐서(tensor)는 배열(Array)나 행렬(matrix)과 매우 유사한 특수한 자료구조
- PyTorch에서는 텐서를 사용하여 모델의 입력과 출력 그리고 모델의 매개변수들을 부호화(encode)함
- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하며 NumPy의 ndarray와 유사함
- 실제로 텐서와 NumPy 배열(Array)은 종종 동일한 내부 메모리를 공유할 수 있어 데이터를 복사할 필요가 없음
- 텐서는 또한 자동 미분에 최적화되어 있음

In [1]:
import torch
import numpy as np

## 텐서(tensor) 초기화
- 텐서는 여러가지 방법으로 초기화할 수 있음
# 데이터로부터 직접(directly) 생성하기
- 데이터로부터 직접 텐서를 생성할 수 있음
- 데이터의 자료형(data type)은 자동으로 유추함

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

### NumPy 배열로부터 생성하기
- 텐서는 NumPy 배열로 생성할 수 있음

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### 다른 텐서로부터 생성하기
- 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지함

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0526, 0.2916],
        [0.7641, 0.9474]]) 



### 무작위(random) 또는 상수(constant) 값을 사용하기
- shape은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 출력 텐서의 차원을 결정함

In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5334, 0.2418, 0.6037],
        [0.1197, 0.4772, 0.5735]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성(Attribute)
- 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서 연산(Operation)
- 전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등, 100가지 이상의 텐서 연산들을 수행할 수 있음


In [8]:
# GPU가 존재하면 텐서를 이동함
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

### NumPy식의 표준 인덱싱과 슬라이싱

In [10]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 텐서 합치기
- torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있음

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### 산술 연산(Arithmetic operations)

In [13]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산함
# y1, y2, y3은 모두 같은 값을 가짐
# tensor.T는 텐서의 전치(transpose)를 반환

y1 = tensor @ tensor.T # @ -> 행렬곱셈 연산자
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱(element-wise product)를 계산함
# z1, z2, z3는 모두 같은 값을 가짐
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 단일-요소(single-element) 텐서
- 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서인 경우, item()을 사용하여 python 숫자 값으로 변환할 수 있음

In [14]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### 바꿔치기(in-place) 연산
- 연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 가짐
  - 예를 들어: x.copy_(y)나 x.t_()는 x를 변경함
- 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivate) 계산에 문제가 발생할 수 있음
  - 사용을 권장하지 않음

In [15]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [16]:
print(f"{tensor} \n")
tensor.mul_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[30., 25., 30., 30.],
        [30., 25., 30., 30.],
        [30., 25., 30., 30.],
        [30., 25., 30., 30.]])


## NumPy 변환(Bridge)
- CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 떄문에, 하나를 변경하면 다른 하나도 변경됨
### 텐서를 NumPy 배열로 변환하기

In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy 배열을 텐서로 변환하기

In [19]:
n = np.ones(5)
t = torch.from_numpy(n)

In [20]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
